### ISSUE TITLE
navbar for the website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/bingo#3]
- [ ] design a navbar component inside the `(home)/components/Navbar.tsx`
- [ ] attach the unique logo for game
- [ ] transition effect in the navbar
- [ ] Add sign-in/sign-up buttons
- [ ] responsive for the small devices also
- [ ] use tailwind css to design the navbar

**Comment by kratik1237** [comment]
please assign the issue.
@Avdhesh-Varshney

**Comment by Mehak-Mattoo** [comment]
I want to work on it as well @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@Mehak-Mattoo go ahead.
