### ISSUE TITLE
Footer of the website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/bingo#4]
- [ ] design a footer component inside the `(home)/components/Footer.tsx`
- [ ] attach the unique logo of game
- [ ] transition effect in the footer
- [ ] one line explanation about the game
- [ ] designed name of `Bingo Game` with discussed font style
- [ ] responsive for the small devices also
- [ ] use tailwind css to design the footer

**Comment by Ayushswirlon** [comment]
I am interested plz assign me the issue

**Comment by Avdhesh-Varshney** [comment]
@Ayushswirlon go ahead.

**Comment by Avdhesh-Varshney** [comment]
what's the updates?

**Comment by Ayushswirlon** [comment]
Sorry was try understanding Nordjs for working on this issue but would not be able to so so
