### ISSUE TITLE
main page designing

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/bingo#5]
- [ ] Design the main page component
- [ ] Create a transition UI for the website
- [ ] Intro of game 
- [ ] Standard fonts and font size with proper color code

**Comment by KavyaBS123** [comment]
Hey @Avdhesh-Varshney I would like to work on this 
Can you please assign me this

**Comment by Avdhesh-Varshney** [comment]
@KavyaBS123 go ahead

**Comment by Avdhesh-Varshney** [comment]
what's the updates?

**Comment by KavyaBS123** [comment]
Yup working on it , soon will raise PR

**Comment by KavyaBS123** [comment]
Hey @Avdhesh-Varshney should I modify this page??
![image](https://github.com/Avdhesh-Varshney/bingo/assets/148982177/7a35452f-397d-4037-93e5-ce5e757b1ab1)

**Comment by Avdhesh-Varshney** [comment]
yes, add some creative content, images, with animations.
